# Generated by Django 2.0.5 on 2018-05-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('title', models.CharField(default='', max_length=32, verbose_name='Название')),
                ('region', models.CharField(default='', max_length=32, verbose_name='Регион доставки')),
                ('duration', models.CharField(default='', max_length=32, verbose_name='Срок доставки')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name_plural': 'варианты доставки',
                'verbose_name': 'вариант доставки',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('question', models.CharField(default='', max_length=32, verbose_name='Вопрос')),
                ('answer', models.TextField(default='', verbose_name='Ответ')),
            ],
            options={
                'verbose_name_plural': 'вопросы-ответы',
                'verbose_name': 'вопрос-ответ',
            },
        ),
    ]
