# Generated by Django 2.0.5 on 2018-05-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Modify date')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Modify date')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Title')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('count', models.IntegerField(default=0, verbose_name='Count in stock')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Price')),
                ('discount', models.IntegerField(default=0, verbose_name='Discount')),
                ('photo', models.ImageField(blank=True, default='', upload_to='', verbose_name='Product photo')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
