# Generated by Django 2.0.5 on 2018-05-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180517_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='event_duration',
        ),
    ]
