# Generated by Django 2.0.5 on 2018-05-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_event_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprop',
            name='values',
        ),
    ]
