# Generated by Django 2.0.5 on 2018-05-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_productprop_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprop',
            name='values',
            field=models.ManyToManyField(blank=True, to='shop.PropValue', verbose_name='Значения'),
        ),
    ]
