# Generated by Django 2.0.5 on 2018-05-17 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productprop_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productprop',
            old_name='prop_desc',
            new_name='schema',
        ),
        migrations.AlterField(
            model_name='productprop',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='props', to='shop.Product', verbose_name='Товар'),
        ),
    ]
