# Generated by Django 2.0.5 on 2018-05-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180517_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='props',
            field=models.ManyToManyField(related_name='props', to='shop.PropValue', verbose_name='Параметры'),
        ),
    ]
