# Generated by Django 2.0.5 on 2018-05-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderitem_props'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='props',
            field=models.ManyToManyField(related_name='props', to='shop.ProductProp', verbose_name='Параметры'),
        ),
    ]
