# Generated by Django 2.0.5 on 2018-05-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180518_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Price')),
            ],
            options={
                'verbose_name_plural': 'предложения',
                'verbose_name': 'предложение',
            },
        ),
        migrations.DeleteModel(
            name='DeliveryVariant',
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['ordering'], 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'позиция', 'verbose_name_plural': 'позиции'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at'], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='shop.Product', verbose_name='Product'),
        ),
    ]
