# Generated by Django 2.0.5 on 2018-05-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20180518_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprop',
            name='category_prop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_props', to='shop.CategoryProp', verbose_name='Параметр'),
        ),
    ]
