# Generated by Django 2.0.5 on 2018-05-18 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_productprop_category_prop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprop',
            name='offer',
        ),
        migrations.AddField(
            model_name='productprop',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='props', to='shop.Product', verbose_name='Товар'),
        ),
    ]
