# Generated by Django 2.0.5 on 2018-05-20 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20180520_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('value', models.CharField(default='', max_length=255, verbose_name='Значение')),
                ('category_prop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_props', to='shop.CategoryProp', verbose_name='Параметр')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='props', to='shop.Offer', verbose_name='Предложение')),
            ],
            options={
                'verbose_name_plural': 'параметры',
                'verbose_name': 'параметр',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('waiting', 'Не принят'), ('confirmed', 'Принят'), ('sended', 'Отправлен'), ('completed', 'Доставлен')], default='waiting', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'verbose_name': 'Заказ',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Кол-во')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.Order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name_plural': 'позиции',
                'verbose_name': 'позиция',
            },
        ),
        migrations.RemoveField(
            model_name='productprop',
            name='category_prop',
        ),
        migrations.RemoveField(
            model_name='productprop',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductProp',
        ),
    ]
